project_id = "pxerqticmmpurwmumhyw"

[functions.nowpayments-create]
verify_jwt = false

[functions.nowpayments-webhook]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.start-mining-session]
verify_jwt = false

[functions.get-mining-status]
verify_jwt = false

[functions.complete-mining-session]
verify_jwt = false

[functions.notify-admin-withdrawal]
verify_jwt = false

[functions.notify-admin-payment]
verify_jwt = false
