project_id = "pxerqticmmpurwmumhyw"

[functions.nowpayments-create]
verify_jwt = false

[functions.nowpayments-webhook]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false
